/**
 * Layout Dimension Constants
 */
export const LAYOUT_CONSTANTS = {
  DRAWER_WIDTH_EXPANDED: 260,
  DRAWER_WIDTH_MINI: 76,
  DRAWER_WIDTH_MOBILE: 280,
  HEADER_HEIGHT_DESKTOP: 64,
  HEADER_HEIGHT_MOBILE: 56,
};
